version: 2.1

jobs:
  deploy-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's 
    steps:
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "CircleCi - Smarniture!!"
            
workflows:
  Smarniture:
    jobs:
      - deploy-job