version: 2.1

orbs:
  # orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  deploy-job:
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job will be running (mandatory)
    steps:
      # install node and checkout code
      - node/install:
          node-version: '16.16.0' 
      - run:
          name: Test CircleCi
          command: |
            echo "CircleCi - Smarniture!!"
            echo "By Mohamed Ghanem"
            
workflows:
  Smarniture:
    jobs:
      - deploy-job