version: 2.1

orbs:
  # orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  deploy-job:
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job will be running (mandatory)
    steps:
      # install node and checkout code
      - node/install:
          node-version: '16.16.0'
      # change directory from the .circleci folder to use root-level package.json file
      - checkout
      - run:
          name: Install frontend dependencies
          command: |
            echo "Installing frontend dependencies ..."
            npm run frontend:install
      - run:
          name: Build frontend
          command: |
            echo "Building frontend ..."
            npm run frontend:build
            
workflows:
  Smarniture:
    jobs:
      - deploy-job