version: 2.1

jobs:
  deploy-job:
    steps:
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "CircleCi - Smarniture!!"
            
workflows:
  Smarniture:
    jobs:
      - deploy-job