version: 2.1

orbs:
  # orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job will be running (mandatory)
    steps:
      # install node and checkout code
      - node/install:
          node-version: '16.16.0'
      # change directory from the .circleci folder to use root-level package.json file
      - checkout
      - run:
          name: Install frontend dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            echo "Installing frontend dependencies ..."
            npm run frontend:install
      - run:
          name: Build frontend
          command: |
            echo "Building frontend ..."
            npm run frontend:build
    deploy:
       docker:
        - image: cimg/base:stable # the primary container, where your job will be running (mandatory)
       steps:
        - node/install:
            node-version: '16.16.0' 
        - aws-cli/setup
        - checkout
        - run:
            name: Deploy Frontend
            command: |
              echo "Deploying Frontend ..."
              npm run frontend:deploy
       
workflows:
  Smarniture:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy