version: 2.1

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SO:ME:FIN:G:ER:PR:IN:T"
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "CircleCi - Smarniture!!"
            
workflows:
  Smarniture:
    jobs:
      - deploy-job